"""Run orchestration: the pipelined brief -> storyboard -> judge -> film -> score -> final-cut loop.

One :class:`Run` owns the state of one ad (the exact JSON shape of CONTRACT §6), its :class:`EventBus`, its
run folder and every background task working on it. :class:`RunManager` owns all runs, loads finished runs
from disk on startup and is the single entry point used by the HTTP layer.

Scheduling is *pipelined, never barriered*::

    director ──┬──> music v1 (Lyria) ─────────────────────────────────────────────┐
               └──> anchor (NB2) ──┬──> s1: K variants ─> judge ─(repair)─> winner ─> Omni clip ─┤
                                   ├──> s2: K variants ─> judge ─(repair)─> winner ─> Omni clip ─┼─> final stitch
                                   └──> sN: ...                                                  ┘

Each scene is an independent chain, so scene 1 may already be rendering video while scene 4 is still being
judged. The final cut is produced as soon as every clip and the soundtrack have a version, and any later change
(new clip version, new music version, winner override) triggers a debounced, single-flight re-stitch.

Concurrency model
-----------------
* Everything runs on the single asyncio event loop; state mutations are therefore atomic between ``await``s.
* Every scene has two locks: ``board`` (storyboard rounds: initial, regenerate, restyle) and ``clip`` (Omni
  renders and edits). Operations on the *same* clip serialize (so multi-turn edits chain correctly) while
  different clips run fully in parallel. Global rate limiting lives in :class:`GenMedia`'s semaphores.
* Superseded work is coalesced with generation tokens: if the user picks three winners in quick succession only
  the last re-render actually runs; the same applies to music re-scores.
* Background work is started only through :meth:`Run.spawn`, which converts any exception into ``error`` +
  ``log`` events and a sensible status -- a failing model call can never crash the server.

Version bookkeeping: ``clip.current`` / ``music.current`` hold the ``v`` number (1-based) of the newest *done*
version (0 = none yet); ``final.version`` counts completed stitches.
"""

from __future__ import annotations

import asyncio
import inspect
import json
import logging
import os
import re
import secrets
import statistics
import time
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Awaitable, Callable, Coroutine

from app import media
from app.events import EventBus

log = logging.getLogger("adloop.pipeline")

#: Debounce window for automatic re-stitches after the first final cut (CONTRACT §6.3).
RESTITCH_DEBOUNCE_S = 1.5
#: Debounce before the *first* final cut: short, so time-to-final is not inflated, but long enough to batch the
#: last clip and the soundtrack when they land within a few hundred ms of each other.
FIRST_STITCH_DEBOUNCE_S = 0.25
#: Minimum spacing between two ``metrics`` events (<= 2/s).
METRICS_INTERVAL_S = 0.5
#: Minimum spacing between two ``clip_status: rendering`` progress events for the same clip.
PROGRESS_INTERVAL_S = 0.9
#: Number of NB2 edits generated by a repair round.
REPAIR_VARIANTS = 2
#: Maximum characters kept from any single user instruction.
MAX_INSTRUCTION_CHARS = 600

_RUN_ID_RE = re.compile(r"^[0-9a-f]{8}$")


# --------------------------------------------------------------------------------------------- helpers
def _prompts():
    """Import :mod:`app.prompts` lazily (owned by builder A; keeps this module importable on its own)."""
    from app import prompts  # noqa: WPS433

    return prompts


def _to_dict(obj: Any) -> dict:
    """Normalise a model-layer result (dict, dataclass, pydantic model, TypedDict) to a plain dict."""
    if obj is None:
        return {}
    if isinstance(obj, dict):
        return obj
    for attr in ("model_dump", "to_dict", "dict"):
        fn = getattr(obj, attr, None)
        if callable(fn):
            try:
                out = fn()
                if isinstance(out, dict):
                    return out
            except Exception:  # noqa: BLE001 - try the next strategy
                pass
    try:
        from dataclasses import asdict, is_dataclass

        if is_dataclass(obj):
            return asdict(obj)
    except Exception:  # noqa: BLE001
        pass
    return dict(getattr(obj, "__dict__", {}) or {})


def _filter_kwargs(fn: Callable, kwargs: dict) -> dict:
    """Drop keyword arguments ``fn`` does not accept (shim for optional/additive parameters)."""
    try:
        params = inspect.signature(fn).parameters
    except (TypeError, ValueError):
        return kwargs
    if any(p.kind is inspect.Parameter.VAR_KEYWORD for p in params.values()):
        return kwargs
    return {k: v for k, v in kwargs.items() if k in params}


def _err_text(exc: BaseException, limit: int = 240) -> str:
    """Short, UI-safe error message (GenAIError messages are already UI-safe)."""
    msg = str(exc).strip() or exc.__class__.__name__
    msg = re.sub(r"AIza[0-9A-Za-z_\-]{20,}", "[redacted]", msg)
    return msg if len(msg) <= limit else msg[: limit - 1] + "…"


def _slug(text: str, limit: int = 24) -> str:
    """Filesystem-safe slug for a market name (``"Tokyo · Japanese"`` -> ``"tokyo-japanese"``)."""
    s = re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-")
    return (s[:limit].strip("-") or "market") + "-" + format(zlib.crc32(str(text).encode()) & 0xFFFF, "04x")


def _clip_instruction(text: str | None) -> str | None:
    """Trim a user instruction; empty strings become None."""
    if text is None:
        return None
    text = str(text).strip()
    return text[:MAX_INSTRUCTION_CHARS] or None


def _percentile(values: list[int], pct: float) -> int | None:
    """Nearest-rank percentile of a list of latencies (None if empty)."""
    if not values:
        return None
    ordered = sorted(values)
    k = max(0, min(len(ordered) - 1, int(round(pct / 100.0 * len(ordered) + 0.5)) - 1))
    return int(ordered[k])


def new_run_id() -> str:
    """8-char lowercase hex run id."""
    return secrets.token_hex(4)


def valid_run_id(run_id: str) -> bool:
    return bool(_RUN_ID_RE.match(run_id or ""))


def _atomic_write_json(path: Path, obj: Any) -> None:
    """Write JSON to ``path`` via a temp file + rename so readers never see a torn file."""
    tmp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    tmp.write_text(json.dumps(obj, ensure_ascii=False, indent=1, default=str), encoding="utf-8")
    os.replace(tmp, path)


# --------------------------------------------------------------------------------------------- run
@dataclass
class _SceneRuntime:
    """In-memory (non-persisted) coordination primitives for one scene."""

    board: asyncio.Lock = field(default_factory=asyncio.Lock)   # storyboard rounds
    clip: asyncio.Lock = field(default_factory=asyncio.Lock)    # Omni renders / edits
    winner_ready: asyncio.Event = field(default_factory=asyncio.Event)
    next_idx: int = 0            # next global variant index to hand out
    render_token: int = 0        # bumped by select/regenerate; stale re-renders are skipped


class Run:
    """State, event bus and background work of one ad run."""

    def __init__(self, manager: "RunManager", state: dict, *, history: list[dict] | None = None,
                 product_image: bytes | None = None) -> None:
        self.manager = manager
        self.gm = manager.gm
        self.settings = manager.settings
        self.state = state
        self.id: str = state["id"]
        self.dir: Path = manager.data_dir / self.id
        self.bus = EventBus(self.id, self.dir, state["created_at"], history=history)
        self.product_image = product_image
        self._anchor_bytes: bytes | None = None
        self._scenes: dict[str, _SceneRuntime] = {}
        self._tasks: set[asyncio.Task] = set()
        self._main_task: asyncio.Task | None = None
        # final-cut scheduling
        self._stitch_task: asyncio.Task | None = None
        self._stitch_dirty = False
        self._stitch_force = False
        self._stitch_wake = asyncio.Event()
        # music coalescing
        self._music_lock = asyncio.Lock()
        self._music_token = 0
        # metrics throttling
        self._metrics_last = 0.0
        self._metrics_handle: asyncio.TimerHandle | None = None
        self._rebuild_runtime()

    # ------------------------------------------------------------------ properties
    @property
    def aspect(self) -> str:
        return self.state["input"].get("aspect", "16:9")

    @property
    def plan(self) -> dict | None:
        return self.state.get("plan")

    @property
    def active(self) -> bool:
        """True while the initial pipeline (brief -> first final cut) is still working."""
        return self._main_task is not None and not self._main_task.done() and self.state["status"] == "running"

    def _rebuild_runtime(self) -> None:
        """(Re)create per-scene runtime primitives from state (used on creation and after a restart)."""
        for sc in self.state.get("scenes", []):
            rt = self._scenes.setdefault(sc["id"], _SceneRuntime())
            rt.next_idx = max([v["idx"] for v in sc.get("variants", [])] + [rt.next_idx - 1]) + 1
            if sc.get("winner") is not None:
                rt.winner_ready.set()

    # ------------------------------------------------------------------ plumbing
    def emit(self, type_: str, **payload: Any) -> dict:
        """Emit one event on the run's bus (never raises)."""
        return self.bus.emit(type_, **payload)

    def save(self) -> None:
        """Persist ``run.json`` atomically. Called after every state change; never raises."""
        try:
            self.dir.mkdir(parents=True, exist_ok=True)
            _atomic_write_json(self.dir / "run.json", self.state)
        except Exception:  # noqa: BLE001 - persistence trouble must not break the pipeline
            log.exception("run %s: failed to persist run.json", self.id)

    def url(self, name: str) -> str:
        return f"/media/{self.id}/{name}"

    def path_for_url(self, url: str | None) -> Path | None:
        """Map a ``/media/<id>/<file>`` URL of this run back to its file path."""
        if not url:
            return None
        name = url.rsplit("/", 1)[-1]
        path = self.dir / name
        return path if path.exists() else None

    async def read_url(self, url: str | None) -> bytes | None:
        """Read the bytes behind a media URL (off the event loop)."""
        path = self.path_for_url(url)
        if path is None:
            return None
        return await asyncio.to_thread(path.read_bytes)

    async def save_asset(self, name: str, data: bytes) -> str:
        """Atomically write an asset into the run folder and return its public URL."""
        await asyncio.to_thread(media.save_bytes, self.dir, name, data)
        return self.url(name)

    def log(self, level: str, msg: str) -> None:
        self.emit("log", level=level, msg=msg)
        getattr(log, "warning" if level == "warn" else level, log.info)("run %s: %s", self.id, msg)

    def fail(self, stage: str, exc: BaseException | str, *, scene_id: str | None = None,
             market: str | None = None) -> str:
        """Report a failure: ``stage`` error event + ``error`` + ``log`` events. Returns the message.

        ``scene_id`` / ``market`` are echoed on the ``stage`` event so the UI can close the matching fan-out
        timer (the rail keys per-scene stages by ``scene_id`` and localize by ``market``).
        """
        msg = exc if isinstance(exc, str) else _err_text(exc)
        extra: dict[str, Any] = {"scene_id": scene_id} if scene_id else {}
        if market:
            extra["market"] = market
        self.emit("stage", stage=stage, status="error", detail=msg, **extra)
        self.emit("error", stage=stage, msg=(f"{scene_id}: {msg}" if scene_id else msg))
        self.log("error", f"{stage}{' ' + scene_id if scene_id else ''} failed: {msg}")
        return msg

    def spawn(self, coro: Coroutine, *, stage: str, scene_id: str | None = None,
              market: str | None = None) -> asyncio.Task:
        """Run ``coro`` in the background; any exception becomes error/log events (never propagates)."""

        async def guarded() -> None:
            try:
                await coro
            except asyncio.CancelledError:
                raise
            except Exception as exc:  # noqa: BLE001 - the whole point is to catch everything
                log.exception("run %s: background task %s failed", self.id, stage)
                self.fail(stage, exc, scene_id=scene_id, market=market)
                if market and market in self.state["localizations"]:
                    self.state["localizations"][market]["status"] = "error"
                    self.emit("localize_status", market=market, status="error", error=_err_text(exc))
                self.save()

        task = asyncio.get_running_loop().create_task(guarded(), name=f"run-{self.id}-{stage}")
        self._tasks.add(task)
        task.add_done_callback(self._tasks.discard)
        return task

    def cancel_all(self) -> None:
        """Cancel every background task (server shutdown)."""
        for task in list(self._tasks):
            task.cancel()
        if self._metrics_handle:
            self._metrics_handle.cancel()
        self.bus.close()

    # ------------------------------------------------------------------ scene helpers
    def scene(self, scene_id: str) -> dict | None:
        return next((s for s in self.state["scenes"] if s["id"] == scene_id), None)

    def plan_scene(self, scene_id: str) -> dict:
        """The plan's scene dict merged with live state (mood/energy may have been changed by edits)."""
        base = next((s for s in (self.plan or {}).get("scenes", []) if s.get("id") == scene_id), {})
        sc = self.scene(scene_id) or {}
        merged = dict(base)
        for key in ("mood", "energy", "title", "beat", "duration_s"):
            if sc.get(key) not in (None, ""):
                merged[key] = sc[key]
        return merged

    def scenes_for_prompts(self) -> list[dict]:
        """Scene dicts (plan + live mood + asset status) handed to music / direction prompts."""
        out = []
        for sc in self.state["scenes"]:
            d = self.plan_scene(sc["id"])
            d["winner_url"] = self.winner_variant(sc)["url"] if self.winner_variant(sc) else None
            d["clip_versions"] = len(sc["clip"]["versions"])
            d["last_instruction"] = next((v.get("instruction") for v in reversed(sc["clip"]["versions"])
                                          if v.get("instruction")), None)
            out.append(d)
        return out

    def clip_seconds(self, sc: dict) -> int:
        """Clip duration for a scene: the planned duration, capped by ``settings.video_seconds``."""
        cap = int(self.settings.video_seconds)
        try:
            planned = int(round(float(sc.get("duration_s") or cap)))
        except (TypeError, ValueError):
            planned = cap
        return max(2, min(cap, planned))

    def total_seconds(self) -> int:
        return sum(self.clip_seconds(sc) for sc in self.state["scenes"]) or int(self.settings.video_seconds)

    @staticmethod
    def winner_variant(sc: dict) -> dict | None:
        if sc.get("winner") is None:
            return None
        return next((v for v in sc["variants"] if v["idx"] == sc["winner"]), None)

    @staticmethod
    def current_clip(sc: dict) -> dict | None:
        cur = sc["clip"].get("current") or 0
        return next((v for v in sc["clip"]["versions"] if v["v"] == cur), None)

    def refs(self, *extra_first: bytes | None) -> list[bytes]:
        """Continuity references: explicit base image(s) first, then the anchor, then the product photo."""
        return [r for r in (*extra_first, self._anchor_bytes, self.product_image) if r]

    async def anchor_bytes(self) -> bytes | None:
        if self._anchor_bytes is None and self.state.get("anchor"):
            self._anchor_bytes = await self.read_url(self.state["anchor"].get("url"))
        return self._anchor_bytes

    # ================================================================== initial pipeline
    def start(self) -> None:
        """Kick off the initial pipeline in the background."""
        self._main_task = self.spawn(self._pipeline(), stage="director")

    async def _pipeline(self) -> None:
        """Director -> (music v1 || anchor -> per-scene chains). The final cut is triggered by the chains."""
        inp = self.state["input"]
        self.emit("run_started", mode=self.state["mode"], input=inp)
        self.save()
        p = _prompts()

        # ---- 1. creative director
        self.emit("stage", stage="director", status="start")
        self.touch_metrics()
        try:
            plan_obj, res = await p.plan_campaign(
                self.gm, brief=inp["brief"], brand=inp.get("brand", ""), aspect=self.aspect,
                n_scenes=inp["n_scenes"], markets=inp.get("markets", []), product_image=self.product_image)
        except Exception as exc:  # noqa: BLE001
            self.fail("director", exc)
            self.state["status"] = "error"
            self.save()
            return
        plan = _to_dict(plan_obj)
        if not plan.get("scenes"):
            self.fail("director", "the creative director returned a plan with no scenes")
            self.state["status"] = "error"
            self.save()
            return
        self._install_plan(plan)
        self.emit("plan", plan=plan)
        self.emit("stage", stage="director", status="done", ms=res.latency_ms,
                  detail=f"{len(plan['scenes'])} scenes · {res.api_path}")
        self.save()

        # ---- 2. fork: music v1 (never waits for images) || anchor -> scene chains
        self.spawn(self.render_music(reason="initial"), stage="music")
        await self._make_anchor()
        chains = [self.spawn(self._scene_chain(sc["id"]), stage="storyboard", scene_id=sc["id"])
                  for sc in self.state["scenes"]]
        await asyncio.gather(*chains, return_exceptions=True)
        # Clips that failed permanently must not block the first final cut forever.
        self.request_stitch()

    def _install_plan(self, plan: dict) -> None:
        """Store the plan and derive the per-scene state skeleton (ids normalised to s1..sN if missing)."""
        seen: set[str] = set()
        for i, sc in enumerate(plan["scenes"], start=1):
            sid = str(sc.get("id") or f"s{i}")
            if sid in seen or not re.match(r"^[A-Za-z0-9_-]{1,16}$", sid):
                sid = f"s{i}"
            seen.add(sid)
            sc["id"] = sid
        self.state["plan"] = plan
        self.state["scenes"] = []
        for sc in plan["scenes"]:
            try:
                energy = float(sc.get("energy", 0.5))
            except (TypeError, ValueError):
                energy = 0.5
            self.state["scenes"].append({
                "id": sc["id"], "title": sc.get("title", ""), "beat": sc.get("beat", ""),
                "mood": sc.get("mood", ""), "energy": energy,
                "duration_s": sc.get("duration_s") or self.settings.video_seconds,
                "variants": [], "judge": [], "winner": None,
                "clip": {"status": "idle", "elapsed_ms": 0, "error": None, "current": 0, "versions": []},
            })
        self._rebuild_runtime()

    async def _make_anchor(self) -> None:
        """NB2 continuity anchor (hero/product reference frame). Failure is non-fatal: scenes run without it."""
        p = _prompts()
        plan = self.plan or {}
        self.emit("stage", stage="anchor", status="start")
        self.touch_metrics()
        builder = getattr(p, "anchor_image_prompt", None) or getattr(p, "anchor_prompt", None)
        try:
            prompt = builder(plan) if callable(builder) else None
        except Exception:  # noqa: BLE001 - fall back to the raw plan prompt
            prompt = None
        if not prompt:
            brand = plan.get("brand", {}) or {}
            prompt = (f"{plan.get('anchor_prompt', '')}\nVisual style: {brand.get('visual_style', '')}. "
                      f"Palette: {', '.join(brand.get('palette', []) or [])}. Clean continuity reference frame, "
                      f"no text.").strip()
        started = self.bus.now_ms()
        try:
            res = await self.gm.generate_image(prompt, refs=[self.product_image] if self.product_image else [],
                                               aspect=self.aspect)
        except Exception as exc:  # noqa: BLE001
            self.fail("anchor", exc)
            self.log("warn", "continuing without a continuity anchor")
            return
        self._anchor_bytes = res.data
        url = await self.save_asset(f"anchor{media.ext_for_mime(res.mime_type)}", res.data)
        self.state["anchor"] = {"url": url, "latency_ms": res.latency_ms}
        self._image_landed(started)
        self.emit("anchor", url=url, latency_ms=res.latency_ms)
        self.emit("stage", stage="anchor", status="done", ms=res.latency_ms)
        self.save()
        self.touch_metrics()

    async def _scene_chain(self, scene_id: str) -> None:
        """One scene end-to-end: K variants -> judge -> optional repair -> winner -> Omni clip."""
        rt = self._scenes[scene_id]
        async with rt.board:
            ok = await self._storyboard_round(scene_id, kind="initial")
        if ok:
            await self.render_clip(scene_id, token=rt.render_token, reason="initial")

    # ================================================================== storyboard
    async def _gen_variants(self, scene_id: str, *, round_: int, kind: str, count: int,
                            prompt: str, refs: list[bytes], seed_base: int) -> list[dict]:
        """Generate ``count`` NB2 variants in parallel, emitting each one the moment it lands."""
        sc = self.scene(scene_id)
        rt = self._scenes[scene_id]
        idxs = list(range(rt.next_idx, rt.next_idx + count))
        rt.next_idx += count

        async def one(idx: int) -> dict | None:
            started = self.bus.now_ms()
            try:
                res = await self.gm.generate_image(prompt, refs=refs, aspect=self.aspect,
                                                   seed=(seed_base + idx) % (2 ** 31))
                if not res.data:
                    raise RuntimeError("image model returned no image")
            except Exception as exc:  # noqa: BLE001
                msg = _err_text(exc)
                self.emit("variant_error", scene_id=scene_id, idx=idx, round=round_, error=msg)
                self.log("warn", f"{scene_id} variant {idx} failed: {msg}")
                self.touch_metrics()
                return None
            name = f"{scene_id}_r{round_}_v{idx}{media.ext_for_mime(res.mime_type)}"
            url = await self.save_asset(name, res.data)
            var = {"idx": idx, "round": round_, "url": url, "latency_ms": res.latency_ms,
                   "api_path": res.api_path, "score": None, "kind": kind}
            sc["variants"].append(var)
            sc["variants"].sort(key=lambda v: v["idx"])
            self._image_landed(started)
            self.emit("variant", scene_id=scene_id, idx=idx, round=round_, url=url,
                      latency_ms=res.latency_ms, api_path=res.api_path, kind=kind)
            self.save()
            self.touch_metrics()
            return var

        self.touch_metrics()
        results = await asyncio.gather(*(one(i) for i in idxs))
        return [v for v in results if v]

    async def _judge(self, scene_id: str, candidates: list[dict], *, round_: int, kind: str) -> dict | None:
        """Vision-judge ``candidates``; store the judgement with scores mapped to global variant idx.

        Returns the stored judge entry, or None when judging failed (callers fall back to the first candidate).
        """
        p = _prompts()
        sc = self.scene(scene_id)
        images = [await self.read_url(v["url"]) for v in candidates]
        pairs = [(v, b) for v, b in zip(candidates, images) if b]
        if not pairs:
            return None
        self.emit("stage", stage="judge", status="start", scene_id=scene_id)
        self.touch_metrics()
        try:
            judgement_obj, res = await p.judge_scene(
                self.gm, plan=self.plan, scene=self.plan_scene(scene_id), variants=[b for _, b in pairs],
                anchor=await self.anchor_bytes())
        except Exception as exc:  # noqa: BLE001
            self.fail("judge", exc, scene_id=scene_id)
            return None
        j = _to_dict(judgement_obj)
        local = [v for v, _ in pairs]
        scores = []
        for raw in j.get("scores", []) or []:
            s = dict(_to_dict(raw))
            try:
                li = int(s.get("index", -1))
            except (TypeError, ValueError):
                continue
            if 0 <= li < len(local):
                s["idx"] = local[li]["idx"]
                try:
                    s["overall"] = round(float(s.get("overall", 0.0)), 1)
                except (TypeError, ValueError):
                    s["overall"] = 0.0
                local[li]["score"] = s["overall"]
                scores.append(s)
        try:
            wi = int(j.get("winner_index", 0))
        except (TypeError, ValueError):
            wi = 0
        if not 0 <= wi < len(local):
            # Out-of-range winner: fall back to the best scored candidate.
            best = max(scores, key=lambda s: s["overall"], default=None)
            wi = next((i for i, v in enumerate(local) if best and v["idx"] == best["idx"]), 0)
        entry = {"round": round_, "kind": kind, "winner_index": local[wi]["idx"],
                 "rationale": str(j.get("rationale", "")), "fix_instructions": str(j.get("fix_instructions", "")),
                 "scores": scores, "latency_ms": res.latency_ms}
        sc["judge"].append(entry)
        self.emit("judge", scene_id=scene_id, round=round_, kind=kind, scores=scores,
                  winner_idx=entry["winner_index"], rationale=entry["rationale"],
                  fix_instructions=entry["fix_instructions"], latency_ms=res.latency_ms)
        self.emit("stage", stage="judge", status="done", scene_id=scene_id, ms=res.latency_ms)
        self.save()
        self.touch_metrics()
        return entry

    async def _storyboard_round(self, scene_id: str, *, kind: str, instruction: str | None = None,
                                by: str = "judge") -> bool:
        """Variants -> judge -> optional repair -> winner for one scene. Caller holds ``board``.

        Returns True when a winner was selected.
        """
        p = _prompts()
        sc = self.scene(scene_id)
        k = int(self.state["input"].get("variants", 4))
        round_ = max([v["round"] for v in sc["variants"]] + [-1]) + 1
        self.emit("stage", stage="storyboard", status="start", scene_id=scene_id,
                  detail=f"{k} variants · round {round_}" + (f" · {instruction}" if instruction else ""))
        t0 = time.perf_counter()
        prompt = p.scene_image_prompt(self.plan, self.plan_scene(scene_id), instruction=instruction)
        seed_base = zlib.crc32(f"{self.id}:{scene_id}".encode())
        variants = await self._gen_variants(scene_id, round_=round_, kind=kind, count=k, prompt=prompt,
                                            refs=self.refs(), seed_base=seed_base)
        if not variants:
            msg = self.fail("storyboard", "every storyboard variant failed", scene_id=scene_id)
            if not sc["clip"]["versions"]:
                self._set_clip_status(scene_id, "error", error=msg)
            return False
        self.emit("stage", stage="storyboard", status="done", scene_id=scene_id,
                  ms=int((time.perf_counter() - t0) * 1000), detail=f"{len(variants)}/{k} variants")

        judged = await self._judge(scene_id, variants, round_=round_, kind=kind)
        winner = next((v for v in variants if judged and v["idx"] == judged["winner_index"]), variants[0])

        # ---- self-repair: NB2 edit of the winner guided by the judge's fix instructions, then re-judge.
        repairs_done = sum(1 for j in sc["judge"] if j.get("kind") == "repair")
        best = winner.get("score")
        if (judged and best is not None and best < float(self.settings.judge_threshold)
                and repairs_done < int(self.settings.max_repair_rounds)):
            fix = judged.get("fix_instructions") or "fix composition, artifacts and brand consistency"
            base = await self.read_url(winner["url"])
            r_round = round_ + 1
            self.log("info", f"{scene_id}: best score {best} < {self.settings.judge_threshold} -> repair round")
            self.emit("stage", stage="storyboard", status="start", scene_id=scene_id,
                      detail=f"repair round · {fix[:120]}")
            fix_prompt = p.scene_image_prompt(self.plan, self.plan_scene(scene_id), fix=fix,
                                              instruction=instruction)
            repairs = await self._gen_variants(scene_id, round_=r_round, kind="repair", count=REPAIR_VARIANTS,
                                               prompt=fix_prompt, refs=self.refs(base), seed_base=seed_base + 7919)
            self.emit("stage", stage="storyboard", status="done", scene_id=scene_id,
                      detail=f"repair round · {len(repairs)} edits")
            if repairs:
                rejudged = await self._judge(scene_id, [winner, *repairs], round_=r_round, kind="repair")
                if rejudged:
                    winner = next((v for v in [winner, *repairs] if v["idx"] == rejudged["winner_index"]), winner)

        self.set_winner(scene_id, winner["idx"], by=by)
        return True

    def set_winner(self, scene_id: str, idx: int, *, by: str) -> None:
        sc = self.scene(scene_id)
        sc["winner"] = idx
        var = self.winner_variant(sc)
        self._scenes[scene_id].winner_ready.set()
        self.emit("winner", scene_id=scene_id, idx=idx, url=var["url"] if var else None, by=by)
        self.save()

    # ================================================================== clips
    def _set_clip_status(self, scene_id: str, status: str, *, error: str | None = None,
                         elapsed_ms: int | None = None, persist: bool = True) -> None:
        clip = self.scene(scene_id)["clip"]
        clip["status"] = status
        clip["error"] = error
        if elapsed_ms is not None:
            clip["elapsed_ms"] = elapsed_ms
        payload: dict[str, Any] = {"scene_id": scene_id, "status": status}
        if elapsed_ms is not None:
            payload["elapsed_ms"] = elapsed_ms
        if error:
            payload["error"] = error
        self.emit("clip_status", **payload)
        if persist:
            self.save()

    def _progress_cb(self, scene_id: str) -> Callable[[dict], Awaitable[None]]:
        """Throttled Omni progress callback -> ``clip_status: rendering`` events with live elapsed ms."""
        last = [0.0]

        async def cb(info: dict) -> None:
            try:
                now = time.monotonic()
                if now - last[0] < PROGRESS_INTERVAL_S:
                    return
                last[0] = now
                self._set_clip_status(scene_id, "rendering", elapsed_ms=int(info.get("elapsed_ms") or 0),
                                      persist=False)
            except Exception:  # noqa: BLE001 - progress reporting must never break a render
                log.debug("progress callback failed", exc_info=True)

        return cb

    def _add_clip_version(self, scene_id: str, res: Any, url: str, *, instruction: str | None,
                          kind: str) -> dict:
        clip = self.scene(scene_id)["clip"]
        v = max([x["v"] for x in clip["versions"]] + [0]) + 1
        meta = dict(getattr(res, "meta", None) or {})
        ver = {"v": v, "url": url, "instruction": instruction, "latency_ms": res.latency_ms,
               "api_path": res.api_path, "interaction_id": meta.get("interaction_id"),
               "fallback": meta.get("fallback"), "kind": kind}
        clip["versions"].append(ver)
        clip["current"] = v
        clip["status"] = "done"
        clip["error"] = None
        if self.state["metrics"].get("time_to_first_clip_ms") is None:
            self.state["metrics"]["time_to_first_clip_ms"] = self.bus.now_ms()
        self.emit("clip", scene_id=scene_id, v=v, url=url, instruction=instruction, latency_ms=res.latency_ms,
                  api_path=res.api_path, interaction_id=ver["interaction_id"], fallback=ver["fallback"], kind=kind)
        self.emit("clip_status", scene_id=scene_id, status="done")
        self.save()
        self.touch_metrics()
        self.request_stitch()
        return ver

    async def render_clip(self, scene_id: str, *, token: int, reason: str,
                          instruction: str | None = None) -> None:
        """Omni image-to-video from the scene's winning keyframe (initial render or winner override).

        ``token`` is the scene's render token at request time; if a newer select/regenerate arrived while
        this request waited for the clip lock, the request is dropped (the newer one will render).
        """
        p = _prompts()
        rt = self._scenes[scene_id]
        self._set_clip_status(scene_id, "queued")
        self.touch_metrics()
        async with rt.clip:
            if token != rt.render_token:
                return
            sc = self.scene(scene_id)
            var = self.winner_variant(sc)
            image = await self.read_url(var["url"]) if var else None
            if image is None:
                self._set_clip_status(scene_id, "error", error="no winning keyframe")
                return
            prompt = p.scene_motion_prompt(self.plan, self.plan_scene(scene_id))
            if instruction:
                prompt = f"{prompt}\n\nDirector's note (takes priority): {instruction}"
            self.emit("stage", stage="motion", status="start", scene_id=scene_id, detail=reason)
            self._set_clip_status(scene_id, "rendering", elapsed_ms=0)
            self.touch_metrics()
            try:
                res = await self.gm.generate_video(prompt, image=image, aspect=self.aspect,
                                                   seconds=self.clip_seconds(sc),
                                                   on_progress=self._progress_cb(scene_id))
                if not res.data:
                    raise RuntimeError("video model returned no video")
            except Exception as exc:  # noqa: BLE001
                msg = self.fail("motion", exc, scene_id=scene_id)
                # Keep showing the previous version if there is one.
                self._set_clip_status(scene_id, "done" if sc["clip"]["versions"] else "error", error=msg)
                self.touch_metrics()
                return
            v_next = max([x["v"] for x in sc["clip"]["versions"]] + [0]) + 1
            url = await self.save_asset(f"{scene_id}_clip_v{v_next}.mp4", res.data)
            self._add_clip_version(scene_id, res, url, instruction=instruction,
                                   kind="initial" if reason == "initial" else "rerender")
            self.emit("stage", stage="motion", status="done", scene_id=scene_id, ms=res.latency_ms)

    async def edit_clip(self, scene_id: str, instruction: str, *, interpret: bool = True,
                        kind: str = "edit") -> None:
        """Conversational Omni edit of the scene's current clip (+ mood interpretation in parallel).

        If the interpreter reports ``mood_changed`` the scene mood is updated and the soundtrack re-scored.
        """
        p = _prompts()
        rt = self._scenes[scene_id]
        self._set_clip_status(scene_id, "queued")
        self.touch_metrics()
        # An edit issued before the first keyframe exists waits for the judge (bounded).
        try:
            await asyncio.wait_for(rt.winner_ready.wait(), timeout=600)
        except asyncio.TimeoutError:
            self._set_clip_status(scene_id, "error", error="no keyframe to edit")
            return

        async def interpret_task() -> dict | None:
            if not interpret:
                return None
            try:
                out, _ = await p.interpret_clip_edit(self.gm, plan=self.plan, scene=self.plan_scene(scene_id),
                                                     instruction=instruction)
                return _to_dict(out)
            except Exception as exc:  # noqa: BLE001 - interpretation is advisory
                self.log("warn", f"{scene_id}: edit interpretation failed ({_err_text(exc)})")
                return None

        async with rt.clip:
            sc = self.scene(scene_id)
            cur = self.current_clip(sc)
            var = self.winner_variant(sc)
            image = await self.read_url(var["url"]) if var else None
            video = await self.read_url(cur["url"]) if cur else None
            self.emit("stage", stage="motion", status="start", scene_id=scene_id, detail=f"edit: {instruction}")
            self._set_clip_status(scene_id, "rendering", elapsed_ms=0)
            self.touch_metrics()
            kwargs = _filter_kwargs(self.gm.edit_video, {
                "previous_interaction_id": cur.get("interaction_id") if cur else None,
                "video": video, "image": image, "aspect": self.aspect, "seconds": self.clip_seconds(sc),
                "on_progress": self._progress_cb(scene_id),
                "base_prompt": p.scene_motion_prompt(self.plan, self.plan_scene(scene_id)),
            })
            edit = asyncio.ensure_future(self.gm.edit_video(instruction, **kwargs))
            interp = asyncio.ensure_future(interpret_task())
            try:
                res = await edit
                if not res.data:
                    raise RuntimeError("video model returned no video")
            except Exception as exc:  # noqa: BLE001
                msg = self.fail("motion", exc, scene_id=scene_id)
                self._set_clip_status(scene_id, "done" if sc["clip"]["versions"] else "error", error=msg)
                interp.cancel()
                self.touch_metrics()
                return
            v_next = max([x["v"] for x in sc["clip"]["versions"]] + [0]) + 1
            url = await self.save_asset(f"{scene_id}_clip_v{v_next}.mp4", res.data)
            self._add_clip_version(scene_id, res, url, instruction=instruction, kind=kind)
            self.emit("stage", stage="motion", status="done", scene_id=scene_id, ms=res.latency_ms)
        info = await interp
        if info and info.get("mood_changed"):
            mood = str(info.get("mood") or sc.get("mood") or "").strip()
            energy = info.get("energy", sc.get("energy"))
            self.update_mood(scene_id, mood, energy)
            self.spawn(self.render_music(reason=f"scene {scene_id} → {mood}"), stage="music")

    def update_mood(self, scene_id: str, mood: str | None, energy: Any) -> None:
        """Apply a mood/energy change to a scene (state + plan) and emit ``scene_update``."""
        sc = self.scene(scene_id)
        if sc is None:
            return
        if mood:
            sc["mood"] = str(mood)[:80]
        try:
            sc["energy"] = max(0.0, min(1.0, float(energy)))
        except (TypeError, ValueError):
            pass
        for ps in (self.plan or {}).get("scenes", []):
            if ps.get("id") == scene_id:
                ps["mood"], ps["energy"] = sc["mood"], sc["energy"]
        self.emit("scene_update", scene_id=scene_id, mood=sc["mood"], energy=sc["energy"])
        self.save()

    # ================================================================== music
    async def render_music(self, *, reason: str, instruction: str | None = None) -> None:
        """Lyria (re-)score. Requests are coalesced: while one render runs, only the newest pending one runs next."""
        p = _prompts()
        self._music_token += 1
        token = self._music_token
        async with self._music_lock:
            if token != self._music_token:
                return  # superseded by a newer re-score request
            mus = self.state["music"]
            mus["status"], mus["error"] = "rendering", None
            self.emit("music_status", status="rendering", reason=reason)
            self.emit("stage", stage="music", status="start", detail=reason)
            self.save()
            self.touch_metrics()
            total = self.total_seconds()
            try:
                prompt = p.music_prompt(self.plan, self.scenes_for_prompts(), total_seconds=total,
                                        reason=None if reason == "initial" else reason, instruction=instruction)
                res = await self.gm.generate_music(prompt, seconds=total)
                if not res.data:
                    raise RuntimeError("music model returned no audio")
            except Exception as exc:  # noqa: BLE001
                msg = self.fail("music", exc)
                mus["status"] = "done" if mus["versions"] else "error"
                mus["error"] = msg
                self.emit("music_status", status="error", reason=reason, error=msg)
                self.save()
                self.touch_metrics()
                self.request_stitch()  # a missing soundtrack must not block the first cut
                return
            v = max([x["v"] for x in mus["versions"]] + [0]) + 1
            url = await self.save_asset(f"music_v{v}{media.ext_for_mime(res.mime_type)}", res.data)
            mus["versions"].append({"v": v, "url": url, "prompt": prompt, "latency_ms": res.latency_ms,
                                    "reason": reason, "instruction": instruction})
            mus["current"], mus["status"] = v, "done"
            self.emit("music", v=v, url=url, prompt=prompt, latency_ms=res.latency_ms, reason=reason)
            self.emit("music_status", status="done", reason=reason)
            self.emit("stage", stage="music", status="done", ms=res.latency_ms, detail=reason)
            self.save()
            self.touch_metrics()
            self.request_stitch()

    # ================================================================== final cut
    def _stitch_ready(self) -> bool:
        """First-cut readiness: every scene settled (clip done or failed), >= 1 clip, music settled."""
        scenes = self.state["scenes"]
        if not scenes or self.state.get("plan") is None:
            return False
        have_clip = False
        for sc in scenes:
            if sc["clip"].get("current"):
                have_clip = True
                continue
            if sc["clip"]["status"] != "error":
                return False
        mus = self.state["music"]
        music_settled = bool(mus.get("current")) or mus["status"] == "error"
        return have_clip and music_settled

    def request_stitch(self, *, force: bool = False) -> None:
        """Schedule a (debounced, single-flight) re-stitch. Cheap and safe to call from anywhere."""
        if not force and not self.state["final"].get("version") and not self._stitch_ready():
            return
        self._stitch_dirty = True
        self._stitch_force = self._stitch_force or force
        self._stitch_wake.set()
        if self._stitch_task is None or self._stitch_task.done():
            self._stitch_task = self.spawn(self._stitch_loop(), stage="final")

    async def _stitch_loop(self) -> None:
        """Single consumer of stitch requests: waits for a quiet period, stitches, repeats while dirty."""
        while self._stitch_dirty:
            quiet = FIRST_STITCH_DEBOUNCE_S if not self.state["final"].get("version") else RESTITCH_DEBOUNCE_S
            if self._stitch_force:
                quiet = FIRST_STITCH_DEBOUNCE_S
            while True:  # debounce: restart the window every time another request arrives
                self._stitch_wake.clear()
                try:
                    await asyncio.wait_for(self._stitch_wake.wait(), timeout=quiet)
                except asyncio.TimeoutError:
                    break
            self._stitch_dirty = False
            self._stitch_force = False
            await self._stitch_once()

    async def _stitch_once(self) -> None:
        clips: list[Path] = []
        missing: list[str] = []
        for sc in self.state["scenes"]:
            cur = self.current_clip(sc)
            path = self.path_for_url(cur["url"]) if cur else None
            (clips.append(path) if path else missing.append(sc["id"]))
        if not clips:
            self.log("warn", "final cut skipped: no clips rendered yet")
            return
        if missing:
            self.log("warn", f"final cut without scene(s) {', '.join(missing)} (no clip)")
        mus = self.state["music"]
        cur_m = next((m for m in mus["versions"] if m["v"] == mus.get("current")), None)
        music_path = self.path_for_url(cur_m["url"]) if cur_m else None
        fin = self.state["final"]
        fin["status"] = "rendering"
        self.emit("final_status", status="rendering")
        self.emit("stage", stage="final", status="start", detail=f"{len(clips)} clips")
        self.save()
        t0 = time.perf_counter()
        version = int(fin.get("version") or 0) + 1
        out = self.dir / f"final_v{version}.mp4"
        try:
            duration = await media.stitch(clips, music_path, out, aspect=self.aspect)
        except Exception as exc:  # noqa: BLE001
            msg = self.fail("final", exc)
            fin["status"] = "done" if fin.get("url") else "error"
            self.emit("final_status", status="error", error=msg)
            self.save()
            return
        ms = int((time.perf_counter() - t0) * 1000)
        fin.update({"status": "done", "url": self.url(out.name), "duration_s": round(duration, 2),
                    "version": version})
        first = self.state["metrics"].get("time_to_final_ms") is None
        if first:
            self.state["metrics"]["time_to_final_ms"] = self.bus.now_ms()
        self.emit("final", url=fin["url"], duration_s=fin["duration_s"], version=version)
        self.emit("final_status", status="done")
        self.emit("stage", stage="final", status="done", ms=ms, detail=f"v{version} · {duration:.1f}s")
        if first and self.state["status"] == "running":
            self.state["status"] = "done"
            self.emit("run_done", wall_ms=self.bus.now_ms())
        self.save()
        self.touch_metrics(force=True)

    # ================================================================== user actions
    def action_select(self, scene_id: str, idx: int) -> None:
        """Winner override -> re-render that scene's clip from the chosen keyframe."""
        rt = self._scenes[scene_id]
        rt.render_token += 1
        self.set_winner(scene_id, idx, by="user")
        self.spawn(self.render_clip(scene_id, token=rt.render_token, reason="select"),
                   stage="motion", scene_id=scene_id)

    def action_regenerate(self, scene_id: str, instruction: str | None) -> None:
        """New NB2 round for one scene -> judge -> re-render the clip."""
        rt = self._scenes[scene_id]
        rt.render_token += 1
        token = rt.render_token

        async def job() -> None:
            async with rt.board:
                ok = await self._storyboard_round(scene_id, kind="regenerate", instruction=instruction)
            if ok and token == rt.render_token:
                await self.render_clip(scene_id, token=token, reason="regenerate")

        self.spawn(job(), stage="storyboard", scene_id=scene_id)

    def action_edit(self, scene_id: str, instruction: str) -> None:
        self.spawn(self.edit_clip(scene_id, instruction), stage="motion", scene_id=scene_id)

    def action_music(self, instruction: str | None) -> None:
        reason = f"re-score: {instruction}" if instruction else "re-score"
        self.spawn(self.render_music(reason=reason[:80], instruction=instruction), stage="music")

    def action_final(self) -> None:
        self.request_stitch(force=True)

    def action_direct(self, instruction: str) -> None:
        self.spawn(self._direct(instruction), stage="direct")

    def action_localize(self, markets: list[str]) -> None:
        for market in markets:
            self.spawn(self._localize(market), stage="localize", market=market)

    # ------------------------------------------------------------------ direct the whole ad
    async def _direct(self, instruction: str) -> None:
        """One sentence -> DirectionPlan -> every clip edit + music re-score (+ optional restyle) in parallel."""
        p = _prompts()
        self.emit("stage", stage="direct", status="start", detail=instruction)
        self.touch_metrics()
        t0 = time.perf_counter()
        dplan_obj, res = await p.plan_direction(self.gm, plan=self.plan, scenes_state=self.scenes_for_prompts(),
                                                instruction=instruction)
        dplan = _to_dict(dplan_obj)
        summary = str(dplan.get("summary") or instruction)
        self.state["directions"].append({"instruction": instruction, "summary": summary, "ts": time.time()})
        self.emit("direction", instruction=instruction, summary=summary, plan=dplan)
        self.save()

        for mu in dplan.get("mood_updates", []) or []:
            mu = _to_dict(mu)
            if self.scene(str(mu.get("scene_id"))):
                self.update_mood(str(mu["scene_id"]), mu.get("mood"), mu.get("energy"))

        jobs: list[Awaitable] = []
        restyle = bool(dplan.get("restyle_keyframes"))
        for se in dplan.get("scene_edits", []) or []:
            se = _to_dict(se)
            sid = str(se.get("scene_id"))
            omni = _clip_instruction(se.get("omni_instruction")) or instruction
            if not self.scene(sid):
                continue
            jobs.append(self._restyle_scene(sid, instruction, omni) if restyle
                        else self.edit_clip(sid, omni, interpret=False, kind="direct"))
        music_cfg = _to_dict(dplan.get("music")) if dplan.get("music") is not None else {"rescore": True}
        if music_cfg.get("rescore", True):
            jobs.append(self.render_music(reason=f"direction: {instruction}"[:80],
                                          instruction=_clip_instruction(music_cfg.get("instruction")) or instruction))
        results = await asyncio.gather(*jobs, return_exceptions=True)
        for r in results:
            if isinstance(r, Exception):
                self.fail("direct", r)
        self.emit("stage", stage="direct", status="done", ms=int((time.perf_counter() - t0) * 1000),
                  detail=summary)
        self.save()

    async def _restyle_scene(self, scene_id: str, instruction: str, omni_instruction: str) -> None:
        """Direction with ``restyle_keyframes``: NB2 edit of the winner -> new winner -> fresh Omni render."""
        p = _prompts()
        rt = self._scenes[scene_id]
        await rt.winner_ready.wait()
        rt.render_token += 1
        token = rt.render_token
        async with rt.board:
            sc = self.scene(scene_id)
            base = await self.read_url(self.winner_variant(sc)["url"]) if self.winner_variant(sc) else None
            round_ = max([v["round"] for v in sc["variants"]] + [-1]) + 1
            prompt = p.scene_image_prompt(self.plan, self.plan_scene(scene_id), instruction=instruction)
            self.emit("stage", stage="storyboard", status="start", scene_id=scene_id, detail=f"restyle: {instruction}")
            got = await self._gen_variants(scene_id, round_=round_, kind="restyle", count=1, prompt=prompt,
                                           refs=self.refs(base), seed_base=zlib.crc32(instruction.encode()))
            self.emit("stage", stage="storyboard", status="done" if got else "error", scene_id=scene_id,
                      detail="restyle")
            if got:
                self.set_winner(scene_id, got[0]["idx"], by="user")
        if got and token == rt.render_token:
            await self.render_clip(scene_id, token=token, reason="direct", instruction=omni_instruction)
        elif not got:
            await self.edit_clip(scene_id, omni_instruction, interpret=False, kind="direct")

    # ------------------------------------------------------------------ localization
    async def _localize(self, market: str) -> None:
        """Per market: localize_plan -> NB2 edits of every winning keyframe (parallel) -> Lyria regional variant."""
        p = _prompts()
        locs = self.state["localizations"]
        entry = locs.setdefault(market, {"status": "", "plan": {}, "scenes": [], "music_url": None})
        entry.update({"status": "rendering", "scenes": [], "music_url": None, "error": None})
        self.emit("localize_status", market=market, status="rendering")
        self.emit("stage", stage="localize", status="start", detail=market, market=market)
        self.save()
        t0 = time.perf_counter()
        try:
            lplan_obj, _ = await p.localize_plan(self.gm, plan=self.plan, market=market)
        except Exception as exc:  # noqa: BLE001
            msg = self.fail("localize", exc, market=market)
            entry.update({"status": "error", "error": msg})
            self.emit("localize_status", market=market, status="error", error=msg)
            self.save()
            return
        lplan = _to_dict(lplan_obj)
        entry["plan"] = lplan
        self.emit("localize_plan", market=market, plan=lplan)
        self.save()
        edits = {str(_to_dict(e).get("scene_id")): _to_dict(e).get("nb2_instruction")
                 for e in lplan.get("scene_edits", []) or []}
        slug = _slug(market)

        async def scene_image(sc: dict) -> None:
            var = self.winner_variant(sc)
            base = await self.read_url(var["url"]) if var else None
            if base is None:
                return
            instr = edits.get(sc["id"]) or (f"Localize for {market}: translate any on-image text to "
                                            f"{lplan.get('language', 'the local language')}, adapt setting and "
                                            f"cast culturally, keep composition and product.")
            prompt = p.scene_image_prompt(self.plan, self.plan_scene(sc["id"]), instruction=instr)
            started = self.bus.now_ms()
            try:
                res = await self.gm.generate_image(prompt, refs=self.refs(base), aspect=self.aspect)
            except Exception as exc:  # noqa: BLE001
                self.log("warn", f"localize {market} {sc['id']} failed: {_err_text(exc)}")
                return
            url = await self.save_asset(f"loc_{slug}_{sc['id']}{media.ext_for_mime(res.mime_type)}", res.data)
            entry["scenes"].append({"scene_id": sc["id"], "url": url, "latency_ms": res.latency_ms})
            entry["scenes"].sort(key=lambda s: [x["id"] for x in self.state["scenes"]].index(s["scene_id"]))
            self._image_landed(started)
            self.emit("localize_image", market=market, scene_id=sc["id"], url=url, latency_ms=res.latency_ms)
            self.save()
            self.touch_metrics()

        async def regional_music() -> None:
            total = self.total_seconds()
            try:
                prompt = p.music_prompt(self.plan, self.scenes_for_prompts(), total_seconds=total,
                                        reason=f"localized for {market}",
                                        instruction=lplan.get("music_style") or None)
                res = await self.gm.generate_music(prompt, seconds=total)
            except Exception as exc:  # noqa: BLE001
                self.log("warn", f"localize {market} music failed: {_err_text(exc)}")
                return
            url = await self.save_asset(f"loc_{slug}_music{media.ext_for_mime(res.mime_type)}", res.data)
            entry["music_url"] = url
            self.emit("localize_music", market=market, url=url, latency_ms=res.latency_ms)
            self.save()
            self.touch_metrics()

        self.touch_metrics()
        await asyncio.gather(*(scene_image(sc) for sc in self.state["scenes"]), regional_music())
        ok = bool(entry["scenes"])
        entry["status"] = "done" if ok else "error"
        if not ok:
            entry["error"] = "no localized keyframes were produced"
        self.emit("localize_status", market=market, status=entry["status"], **({} if ok else
                                                                              {"error": entry["error"]}))
        self.emit("stage", stage="localize", status="done" if ok else "error", detail=market, market=market,
                  ms=int((time.perf_counter() - t0) * 1000))
        self.save()

    # ================================================================== metrics
    def _image_landed(self, started_ms: int) -> None:
        """Record one finished image: TTFI and the [start, end] interval used for images/min."""
        now = self.bus.now_ms()
        m = self.state["metrics"]
        m.setdefault("_img_iv", []).append([int(started_ms), now])
        if m.get("time_to_first_image_ms") is None:
            m["time_to_first_image_ms"] = now

    @staticmethod
    def _busy_ms(intervals: list[list[int]]) -> int:
        """Total length of the union of [start, end] intervals (time with >= 1 image request in flight)."""
        total, cur_s, cur_e = 0, None, None
        for s, e in sorted(intervals):
            if cur_e is None or s > cur_e:
                if cur_e is not None:
                    total += cur_e - cur_s
                cur_s, cur_e = s, e
            else:
                cur_e = max(cur_e, e)
        if cur_e is not None:
            total += cur_e - cur_s
        return total

    def compute_metrics(self) -> dict:
        """Recompute the CONTRACT §6 metrics object from state + GenMedia telemetry."""
        st = self.state
        m = st["metrics"]
        img_lat = [v["latency_ms"] for sc in st["scenes"] for v in sc["variants"]]
        if st.get("anchor"):
            img_lat.append(st["anchor"]["latency_ms"])
        for loc in st["localizations"].values():
            img_lat += [s["latency_ms"] for s in loc.get("scenes", [])]
        vids = [v for sc in st["scenes"] for v in sc["clip"]["versions"]]
        vid_lat = [v["latency_ms"] for v in vids]
        wall = self.bus.now_ms() if st["status"] == "running" else (m.get("time_to_final_ms") or m.get("wall_ms")
                                                                     or self.bus.now_ms())
        # Throughput over the time NB2 was actually busy, so idle minutes between user edits don't dilute it.
        image_busy = self._busy_ms(m.get("_img_iv", []))
        inflight = getattr(self.gm, "inflight", None)
        inflight = inflight() if callable(inflight) else inflight
        api_paths: dict[str, str] = {}
        try:
            for model, s in (self.gm.stats() or {}).items():
                if isinstance(s, dict) and s.get("api_path"):
                    api_paths[model] = s["api_path"]
        except Exception:  # noqa: BLE001 - telemetry is best-effort
            pass
        m.update({
            "wall_ms": wall,
            "images_generated": len(img_lat),
            "image_p50_ms": _percentile(img_lat, 50),
            "image_p95_ms": _percentile(img_lat, 95),
            "images_per_min": round(len(img_lat) * 60000 / max(1, image_busy), 1) if img_lat else 0.0,
            "judge_calls": sum(len(sc["judge"]) for sc in st["scenes"]),
            "repair_rounds": sum(1 for sc in st["scenes"] for j in sc["judge"] if j.get("kind") == "repair"),
            "videos_generated": len(vids),
            "video_p50_ms": int(statistics.median(vid_lat)) if vid_lat else None,
            "video_edits": sum(1 for v in vids if v.get("kind") in ("edit", "direct")),
            "music_versions": len(st["music"]["versions"]),
            "inflight": {k: int((inflight or {}).get(k, 0)) for k in ("image", "video", "music", "text")},
            "time_to_first_image_ms": m.get("time_to_first_image_ms"),
            "time_to_first_clip_ms": m.get("time_to_first_clip_ms"),
            "time_to_final_ms": m.get("time_to_final_ms"),
            "api_paths": api_paths,
        })
        return m

    def touch_metrics(self, *, force: bool = False) -> None:
        """Recompute + emit ``metrics``, throttled to at most one event per METRICS_INTERVAL_S."""
        now = time.monotonic()
        if force or now - self._metrics_last >= METRICS_INTERVAL_S:
            if self._metrics_handle:
                self._metrics_handle.cancel()
                self._metrics_handle = None
            self._emit_metrics()
            return
        if self._metrics_handle is None:  # trailing emit so the last change is never lost
            delay = METRICS_INTERVAL_S - (now - self._metrics_last)
            self._metrics_handle = asyncio.get_running_loop().call_later(delay, self._emit_metrics)

    def _emit_metrics(self) -> None:
        self._metrics_handle = None
        self._metrics_last = time.monotonic()
        try:
            metrics = self.compute_metrics()
            self.emit("metrics", metrics={k: v for k, v in metrics.items() if not k.startswith("_")})
        except Exception:  # noqa: BLE001
            log.exception("run %s: metrics computation failed", self.id)

    def public_state(self) -> dict:
        """Run state for ``GET /api/runs/{id}`` (internal ``_`` keys stripped from metrics)."""
        out = dict(self.state)
        out["metrics"] = {k: v for k, v in self.state.get("metrics", {}).items() if not k.startswith("_")}
        return out


# --------------------------------------------------------------------------------------------- manager
class RunManager:
    """Registry of runs: creation, restart recovery and action dispatch."""

    def __init__(self, settings: Any, gm: Any) -> None:
        self.settings = settings
        self.gm = gm
        self.data_dir = Path(settings.data_dir)
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.runs: dict[str, Run] = {}

    # ------------------------------------------------------------------ lifecycle
    def load_existing(self) -> int:
        """Load every ``data/runs/*/run.json`` so finished runs are browsable/replayable after a restart.

        Work that was in flight when the previous process died cannot resume; it is marked as interrupted.
        """
        loaded = 0
        for path in sorted(self.data_dir.glob("*/run.json")):
            run_id = path.parent.name
            if not valid_run_id(run_id) or run_id in self.runs:
                continue
            try:
                state = json.loads(path.read_text(encoding="utf-8"))
                if state.get("id") != run_id:
                    continue
                self._normalise_loaded(state)
                run = Run(self, state, history=EventBus.load_history(path.parent))
                product = next(path.parent.glob("product.*"), None)
                if product is not None:
                    run.product_image = product.read_bytes()
                self.runs[run_id] = run
                loaded += 1
            except Exception:  # noqa: BLE001 - one corrupt run must not stop startup
                log.exception("failed to load run from %s", path)
        log.info("loaded %d existing run(s) from %s", loaded, self.data_dir)
        return loaded

    @staticmethod
    def _normalise_loaded(state: dict) -> None:
        """Fix up statuses of work interrupted by a restart."""
        note = "interrupted by server restart"
        if state.get("status") == "running":
            state["status"] = "done" if (state.get("final") or {}).get("url") else "error"
        for sc in state.get("scenes", []):
            clip = sc.get("clip", {})
            if clip.get("status") in ("queued", "rendering"):
                clip["status"] = "done" if clip.get("current") else "error"
                clip["error"] = None if clip.get("current") else note
        for key in ("music", "final"):
            blk = state.get(key) or {}
            if blk.get("status") == "rendering":
                blk["status"] = "done" if (blk.get("current") or blk.get("url")) else "error"
        for loc in (state.get("localizations") or {}).values():
            if loc.get("status") == "rendering":
                loc["status"] = "done" if loc.get("scenes") else "error"
        state.setdefault("metrics", {})
        state.setdefault("directions", [])
        state.setdefault("localizations", {})

    async def shutdown(self) -> None:
        for run in self.runs.values():
            run.cancel_all()
            run.save()

    # ------------------------------------------------------------------ queries
    def get(self, run_id: str) -> Run | None:
        return self.runs.get(run_id) if valid_run_id(run_id) else None

    def active_count(self) -> int:
        return sum(1 for r in self.runs.values() if r.active)

    def list_runs(self, limit: int = 20) -> list[dict]:
        out = []
        for run in sorted(self.runs.values(), key=lambda r: r.state["created_at"], reverse=True)[:limit]:
            st = run.state
            thumb = (st.get("anchor") or {}).get("url")
            if not thumb:
                thumb = next((Run.winner_variant(sc)["url"] for sc in st.get("scenes", [])
                              if Run.winner_variant(sc)), None)
            out.append({"id": st["id"], "campaign_name": (st.get("plan") or {}).get("campaign_name")
                        or (st["input"].get("brief", "")[:48]), "status": st["status"],
                        "created_at": st["created_at"], "thumb": thumb,
                        "final_url": (st.get("final") or {}).get("url")})
        return out

    def showcase_id(self) -> str | None:
        env = os.getenv("ADLOOP_SHOWCASE_RUN", "").strip()
        if env and env in self.runs:
            return env
        done = [r for r in self.runs.values() if (r.state.get("final") or {}).get("url")]
        return max(done, key=lambda r: r.state["created_at"]).id if done else None

    # ------------------------------------------------------------------ creation
    def create_run(self, *, brief: str, brand: str, aspect: str, n_scenes: int, variants: int,
                   markets: list[str], product_image: bytes | None, product_mime: str | None = None) -> Run:
        """Create the run folder + initial state and start the pipeline in the background."""
        run_id = new_run_id()
        while run_id in self.runs or (self.data_dir / run_id).exists():
            run_id = new_run_id()
        state = {
            "id": run_id, "status": "running", "mode": "mock" if self.gm.mock else "live",
            "created_at": time.time(),
            "input": {"brief": brief, "brand": brand, "aspect": aspect, "n_scenes": n_scenes,
                      "variants": variants, "markets": markets, "has_product_image": bool(product_image)},
            "plan": None, "anchor": None, "scenes": [],
            "music": {"status": "idle", "current": 0, "error": None, "versions": []},
            "final": {"status": "idle", "url": None, "duration_s": None, "version": 0},
            "directions": [], "localizations": {}, "metrics": {},
        }
        run = Run(self, state, product_image=product_image)
        run.dir.mkdir(parents=True, exist_ok=True)
        if product_image:
            media.save_bytes(run.dir, f"product{media.ext_for_mime(product_mime or 'image/png')}", product_image)
        run.save()
        self.runs[run_id] = run
        run.start()
        return run
